### ISSUE TITLE
problem with starting the server

### ISSUE THREAD

**Issue by CEKTAHT0** [42MonthsAfter/server#124]
Friends. There is a problem with starting the server. Gives the following error
Mods: @TraderPlus
Version 1.12.153904
Fault address: 53B107F5 00:53B107F5 Unknown module
file: Expansion
world: deerisle
Prev. code bytes: 2B D0 48 63 41 5C 48 8B 49 60 4D 63 DA 4C 23 D8
Fault code bytes: 4A 8B 0C D9 48 85 C9 74 31 4C 63 44 24 28 8B D3
Help me with some advice. How to fix it and start the server. Thanks

**Comment by 42MonthsAfter** [comment]
Start the server? Do you mean you get this when you try to join or sign in?

**Comment by CEKTAHT0** [comment]
I can't start the server. The server starts to start and at a certain point disconnects without starting. And the rtp file has the error described above. It swears at the last connected mod and it does not matter what it is. The error is basically the same. Thanks

**Comment by 42MonthsAfter** [comment]
You didn't answer the question. Are you:

1. Attempting to join the server we host and are unable to?

2. Downloading our server files and attempting to host your own version of our server?

You keep saying the server can't start, which reads to me that you have downloaded our files and are attempting to host a server yourself.  Is that correct?

**Comment by CEKTAHT0** [comment]
Hello. Yes, I am trying to start your server on my computer and I get the error described above. After all, the files are posted by you in free access or are you against it?

**Comment by CEKTAHT0** [comment]
I am from Russia, I write messages through Google Translator. Perhaps this is why the message's thought is slightly distorted)

**Comment by 42MonthsAfter** [comment]
Got it! You won't be able to just download our files and start for the following reasons:

1. All personal information has been removed
2. I don't publish other creator's work so that means there are no mod files in this repo
3. There are a lot of sections that I don't upload for security reasons.

What you can do is install your own fresh install, download all the mods yourself then use our xml tables, profile settings, etc if you see something that you want to duplicate.

There is no way to do a 1:1 clone of our server though. These files are just to help you spin up your own but require you to get it running yourself.

**Comment by CEKTAHT0** [comment]
Thank you for your answer. Very sorry. The server in my opinion is very interesting, you are well done. I wish you and your project every success.

**Comment by 42MonthsAfter** [comment]
You are always welcome to play with us!!! We would love to have you join.

Please let me know if I can help in any way with your local server. More than happy to. discord.42monthsafter.com
